spring.application.name=sslms

# MQTT Settings
mqtt.broker.url=mqtt://broker.emqx.io:1883
mqtt.clientId=server-backend

# PostgreSQL Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/sslms_db
spring.datasource.username=admin
spring.datasource.password=strongpassword
spring.jpa.hibernate.ddl-auto=update