spring.application.name=sslms

# MQTT Settings
mqtt.broker.url=tcp://broker.emqx.io:1883
mqtt.clientId=server-backend-0101

# PostgreSQL Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/sslms_db
spring.datasource.username=admin
spring.datasource.password=strongpassword
spring.jpa.hibernate.ddl-auto=update

# Cron Expression: Second Minute Hour Day Month DayOfWeek
# This example runs at 19:00 (7 PM), 00:00 (Midnight), and 05:00 (5 AM)
sslms.sync.schedule=0 0 19,0,5 * * *